import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int input = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int counter = 0;
		int stat2 = 0;
		int stat3 = 0;
		int stat4 = 0;
		double totalChildren = 0;
 		
		while (input > counter){
			int i = 0;
		    int j = 0;

		    while (i == 0 || j == 0) {
		        double x = generator.nextDouble();

	            if (x >= 0.5){
			    i++;

		        } else {
		        j++;
		    }
		}

		int sum = i + j;
		totalChildren += sum;
		
		
		if (sum == 2){
			stat2++;
		} else if (sum == 3){
			stat3++;
		} else if (sum >= 4){
			stat4++;
		}
		counter++;
        
		}
		double average = totalChildren / input;

		System.out.println("Average: "+average+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+stat2);
		System.out.println("Number of families with 3 children: "+stat3);
		System.out.println("Number of families with 4 or more children: "+stat4);
		if (stat2 > stat3 && stat2 > stat4){
			System.out.println("The most common number of children is 2.");
		} else if (stat3 > stat2 && stat3 > stat4){
			System.out.println("The most common number of children is 3.");
		} else if (stat4 > stat2 && stat4 > stat3){
			System.out.println("The most common number of children is 4 or more.");
		}
		}
	
}

		    
	

